server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081
spring:
  output:
    ansi:
      enabled: detect
  data:
    web:
      pageable:
        one-indexed-parameters: true
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
app:
  auth:
    tokenIssuer: pups_load_server_token_issuer
    tokenSecret: 54C77CCD79BDE584FA3E77CBA09EA460
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  ncp:
    region-name: kr-standard
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    object-storage:
      end-point: "https://kr.object.ncloudstorage.com"
      bucket-name: "pupsroad-public"



api:
  redis-key-prefix: "pupsroad:"

naver: # !! 임시 정보 !! 발송번호 신청 후 변경 필요
  sens:
    service-id: ncp:sms:kr:253155718577:lfin_sms
    endpoint: https://sens.apigw.ntruss.com
    sms-url: /sms/v2/services/${naver.sens.service-id}/messages
    access-key: kZwtz74pvrHbXDPG1eGQ
    secret-key: 37EaARATd2m59nb1MaNXi9vuSQx6g682h1lYu0Ru
    sender-no: "0269597414"